import Head from "next/head";
import { useEffect, useState } from "react";

interface TodoListItem {
  id: string;
  text: string;
  done: boolean;
}

interface TodoListResponse {
  todoList: TodoListItem[];
}

export default function Home() {
  const [todoList, setTodoList] = useState<TodoListItem[]>([]);

  useEffect(() => {
    fetch("/api/todo", {
      method: "GET",
    })
      .then((response) => response.json() as Promise<TodoListResponse>)
      .then((data) => setTodoList(data.todoList))
      .catch((error) => console.log("error getting todolist", error));
  }, []);

  function handleTodoChange(id: string) {
    setTodoList(
      todoList.map((item) =>
        item.id === id ? { ...item, done: !item.done } : item,
      ),
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-50 to-slate-100">
        <div className="flex min-h-96 min-w-96 flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4">
          <h1 className="text-2xl font-bold">Todo List</h1>
          {todoList.map((item) => {
            return (
              <div className="flex gap-2" key={item.id}>
                <input
                  type="checkbox"
                  checked={item.done}
                  onChange={() => handleTodoChange(item.id)}
                />
                <p className="text-sm">{item.text}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
